### PR TITLE
Kleine Korrekturen testweise

### PR DESCRIPTION
**Pull request by MarBai**
Hallo,
bin gerade neu in die Gruppe gekommen und versuche mich hiermit an der ersten Datei.
Habe das GitHub-Tutorial gemacht und hoffe, nun auch hier alles richtig gemacht zu haben.
Ich wäre für Rückmeldungen dankbar.
Dann würde ich gleich weitermachen :)

### CODE REVIEW

**Comment by HaploX1** [comment]
Looks good. I've merged it into the main branch :)
One thing: Try to make the comments in english please, even if it's for the german translation, it should be readable for the developer. And as his language is english..
Just my oppinion :)

**Comment by MarBai** [comment]
Thats no problem for me. I´m sharing this oppinion. I just need to get used to it. :)
Please answer my issue question too. I need to know this about merging pull requests :) 
And what about testing ingame? Something i need to know?

**Comment by HaploX1** [comment]
It wasn't a problem to merge your branch into the main branch.
I'm using SourceTree for it. It's a bit more comfortable to handle than the web interface. But both works.

For the mechanical parts:
I'm not sure about it. If you take a look into the original, you'll see, that it's even there not marked as a mechanical body part (only as a body part).
Another problem is the length. You should always test your translation befor sending it to GitHub.
The additional parts are ok, but I'm really unsure about how the 'mechanischer Mittelfinger (links)' for example look in game. I haven't tested it, as I'm a bit short on time right now.
For the tests:
Just delete everything in the Core/Language/German folder and replace it with the GitHub variant.
At the next start the new language will be used and you can test it for errors.

**Comment by MarBai** [comment]
Thanks for the whole bunch of advises. I am giving my best. I have send much more pull requests recently before i read your answer.

2 Steps are possible now.

1. You look over my additions and tell me then to test them
2. I test them first and then i tell you to watch over it

Perhaps you can tell me the most wise way in this.

**Comment by HaploX1** [comment]
If you can, you can make the changes also on the main branch. This way you doesn't need to wait for me to look over it (which I'll do whenever I have time).

For the recognition of your work:
I'll add you to the list of translators if you've helped over at least two alphas.
Hopefully that is ok with you?

**Comment by MarBai** [comment]
Hey Markus,

sure i can make the changes in master branch too. but 

1) im a little worried about making mistakes
2) i think comparing and discussing about changes is the reason we use this platform
3) i dont know if the changes are really ok or working, because i never tested them ingame, that is why i asked about in the last comment. thats why i need to know if i should first test them all and then send pull requests or the other way round

relating to translator list: everything is fine

one more question:

the work on translations is completely voluntary right, i mean, completely without getting rewards from ludeon? just for information :)

**Comment by HaploX1** [comment]
Ok, it is ok to make a second branch. I'll just merge them when I have time :)
And for your no. 3: I think you should always try to test them first before updating the repository.
If you don't have the time for that, that's also ok. But if you have the time, it is better to test them and also look into the output_log.txt file for any possible problems that RimWorld has with the translation files.

And for your last question: 
Yes it's completely voluntary. At least I don't get any money, just my name in the credits :)
Did you read my last comment about the adding of your name when you helped for at least two alphas? Is that ok with you?

**Comment by MarBai** [comment]
Yes, i read that. I completely agree with that, very cool :)

Hopefully, there is enough work to do in the coming alphas i can help with. I think, ill finish with the whole actual translation in a few days and then we have to wait for next versions.

**Pull request merged**
